orbs:
  datree: datree/policy@1.0.6

description: A circle-ci job to enforce Datree's pull request title convention rule

jobs:
  my_job:
    docker:
      - image: 'circleci/node:10'
    steps:
      - datree/pull-request-title-convention

version: 2.1
workflows:
  main:
    jobs:
      - my_job:
          context: github-token-context
